# fly.toml app configuration file generated for hungdo2003-swp391-koi-delivery-deploy on 2024-11-15T12:17:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hungdo2003-swp391-koi-delivery-deploy'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
